### ISSUE TITLE
Running quantitative traits

### ISSUE THREAD

**Issue by ABThijssen** [emkoch/smilenfer#1]
Hi,

I want to run smilenfer for some quantitative traits. I have been able to reproduce the test trait (bc), but am wondering what I should change in the analysis pipeline to run quantitative traits. I have noticed that I should at least change some things in the test_run.yml file, but am not sure which parts to change and which not. Also, should I change anything else somewhere?

Thanks a lot!
Anaïs

**Comment by emkoch** [comment]
Hi Anaïs,

There is actually nothing in the analysis pipeline specific to quantitative versus disease traits. 

This part of the config file references trait types:
```
trait_files:
  BC: "clumped.genome_wide_ash.bc.max_r2.tsv"
trait_types:
  BC: "disease"
trait_type_abbrevs:
  disease: "Disease"
```
The entries here about trait types don't affecting anything except some plots.

If you are comfortable then following the pipeline in example_trait to process the GWAS summary statistics then nothing else in the config file would need to be altered aside from adding the new traits.

Thank you for trying out our software. Please let me know if that solves things or if there is anything else I can help with or improve in the code.

Evan
